import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lib.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Muhammad Akbar
 */
public class HalamanUtama extends javax.swing.JFrame {

    protected void showdata() {
        DefaultTableModel tabelsayur = new DefaultTableModel();
        tabelsayur.addColumn("No");
        tabelsayur.addColumn("Nomor Buku");
        tabelsayur.addColumn("Penerbit");
        tabelsayur.addColumn("Nama Penulis");
        tabelsayur.addColumn("Judul");
        tabelsayur.addColumn("Jenis");
        tabelsayur.addColumn("Stok");
        tabelsayur.addColumn("Harga");
        try {
            int i = 1;
            String sql = "select * from data_buku";
            java.sql.Connection connect = (Connection)koneksi.configDB();
            java.sql.Statement stm = connect.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()) {
                tabelsayur.addRow(new Object[]{i++,
                    res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7)});
            }
           tabel_buku.setModel(tabelsayur);
        } 
        catch (SQLException e) {
        }
    }
    private void reset_kolom(){
        txtnobuku.setText(null);
        txtjudul.setText(null);
        combojenis.setSelectedItem("Pilih Jenis");
        txtstok.setText(null);
        txtharga.setText(null);
        txtnamapenerbit.setText(null);
        txtnamapenulis.setText(null);
    }
    
    public HalamanUtama() {
        initComponents();
        scalenow();
        showdata();
    }
    public Connection conn;
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        delete = new javax.swing.JButton();
        create = new javax.swing.JButton();
        update = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_buku = new javax.swing.JTable();
        txtnamapenulis = new javax.swing.JTextField();
        txtnamapenerbit = new javax.swing.JTextField();
        txtnobuku = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtharga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        combojenis = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 0));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setResizable(false);
        setSize(new java.awt.Dimension(780, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(142, 186, 168));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        delete.setText("Hapus");
        delete.setBorder(null);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 160, 40));

        create.setText("Tambah");
        create.setBorder(null);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });
        create.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                createKeyPressed(evt);
            }
        });
        jPanel2.add(create, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 160, 40));

        update.setText("Update");
        update.setBorder(null);
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel2.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 160, 40));

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 160, 40));

        Logout.setFont(new java.awt.Font("Gill Sans MT", 1, 18)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setText("Log Out");
        Logout.setContentAreaFilled(false);
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });
        jPanel2.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 110, 30));

        tabel_buku = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabel_buku.getTableHeader().setReorderingAllowed(false);
        tabel_buku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "value1", "value2", "value3", "value4"
            }
        ));
        tabel_buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_bukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_buku);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 700, 170));

        txtnamapenulis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapenulisActionPerformed(evt);
            }
        });
        txtnamapenulis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamapenulisKeyPressed(evt);
            }
        });
        jPanel2.add(txtnamapenulis, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, -1));

        txtnamapenerbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamapenerbitActionPerformed(evt);
            }
        });
        txtnamapenerbit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamapenerbitKeyPressed(evt);
            }
        });
        jPanel2.add(txtnamapenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 240, -1));

        txtnobuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnobukuActionPerformed(evt);
            }
        });
        txtnobuku.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnobukuKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnobukuKeyReleased(evt);
            }
        });
        jPanel2.add(txtnobuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 240, -1));

        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });
        txtjudul.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtjudulKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjudulKeyTyped(evt);
            }
        });
        jPanel2.add(txtjudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 240, -1));

        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });
        txtstok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtstokKeyPressed(evt);
            }
        });
        jPanel2.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 240, -1));

        txtharga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthargaActionPerformed(evt);
            }
        });
        txtharga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthargaKeyPressed(evt);
            }
        });
        jPanel2.add(txtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 240, -1));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nama_Penulis");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 100, 20));

        jLabel3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Judul");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, -1));

        jLabel4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jenis");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, -1));

        jLabel5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Stok");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harga");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        combojenis.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        combojenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Komik", "Pelajaran", "Novel" }));
        combojenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combojenisActionPerformed(evt);
            }
        });
        jPanel2.add(combojenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 110, -1));

        jLabel7.setBackground(new java.awt.Color(235, 235, 235));
        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Data Buku");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 230, -1));

        jLabel9.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nomor_Buku");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, 20));

        jLabel10.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nama_Penerbit");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, 20));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 500));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
            try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin?", "Message", JOptionPane.YES_NO_OPTION);
            switch(opsi){
            case JOptionPane.YES_OPTION:
                String jenis = (String) combojenis.getSelectedItem();
//                if (combojenis.getSelectedItem().toString() == "Pilih Jenis"){
//                JOptionPane.showMessageDialog(null, "Pilih Jenis Buku!", "ERROR", JOptionPane.ERROR_MESSAGE);
//                }else if(combojenis.getSelectedItem().toString() != "Pilih Jenis"){
                String sql = "UPDATE data_buku SET nomor_buku='"+ txtnobuku.getText()+"',penerbit='"
                                                         +txtnamapenerbit.getText()+"',nama_penulis='"
                                                         +txtnamapenulis.getText()+"',judul='"
                                                         +txtjudul.getText()+"',stok='"
                                                         +txtstok.getText()+"',harga='"
                                                         +txtharga.getText()+"',jenis='"
                                                         + jenis +"' WHERE nomor_buku='"+txtnobuku.getText()+"'";
                java.sql.Connection connect = (Connection)koneksi.configDB();
                java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                pstm.execute();
                JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                break;
                //}
            case JOptionPane.NO_OPTION:
                 JOptionPane.showMessageDialog(null, "Okeh :) ");
                break;
            default:
                 break;     
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        showdata(); 
        reset_kolom();// TODO add your handling code here:
    }//GEN-LAST:event_updateActionPerformed

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
           try{
            String jenis = (String) combojenis.getSelectedItem();
            if (combojenis.getSelectedItem().toString() == "Pilih Jenis"){
                JOptionPane.showMessageDialog(null, "Pilih Jenis Buku!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            else if (combojenis.getSelectedItem().toString() != "Pilih Jenis"){
            String sql = "INSERT INTO data_buku VALUES ('"+txtnobuku.getText()+"','"
                                                           +txtnamapenerbit.getText()+"','"
                                                           +txtnamapenulis.getText()+"','"
                                                           +txtjudul.getText()+"','"
                                                           +txtstok.getText()+"','"
                                                           +txtharga.getText()+"','"
                                                           + jenis +"')";
            java.sql.Connection connect = (Connection)koneksi.configDB();
            java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        showdata();
        reset_kolom();
        //this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_createActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
         try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Message", JOptionPane.YES_NO_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    String sql = "DELETE FROM data_buku WHERE nomor_buku='"+txtnobuku.getText()+"'";
                    java.sql.Connection connect = (Connection)koneksi.configDB();
                    java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "Okeh :) ");
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        showdata();
        reset_kolom();
    }//GEN-LAST:event_deleteActionPerformed

    private void tabel_bukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_bukuMouseClicked

        int baris = tabel_buku.rowAtPoint(evt.getPoint());
        String nobuku = tabel_buku.getValueAt(baris, 1).toString();
        txtnobuku.setText(nobuku);
        
        String namaterbit = tabel_buku.getValueAt(baris, 2).toString();
        txtnamapenerbit.setText(namaterbit);

        String namapen = tabel_buku.getValueAt(baris, 3).toString();
        txtnamapenulis.setText(namapen);
        
        String judul = tabel_buku.getValueAt(baris, 4).toString();
        txtjudul.setText(judul);
        
        String stok = tabel_buku.getValueAt(baris, 5).toString();
        txtstok.setText(stok);

        String harga = tabel_buku.getValueAt(baris, 6).toString();
        txtharga.setText(harga);
        
        String jen = tabel_buku.getValueAt(baris, 7).toString();
        combojenis.setSelectedItem(jen);

    }//GEN-LAST:event_tabel_bukuMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
          try{
            int opsi = JOptionPane.showConfirmDialog(null, "Yaqin Dek??", "Message", JOptionPane.YES_NO_CANCEL_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    JOptionPane.showMessageDialog(null, "Log Out Berhasil");
                    new lojin().show();
                    this.dispose();
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "Okeh :)");
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }                        
    }//GEN-LAST:event_LogoutActionPerformed

    private void combojenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combojenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combojenisActionPerformed

    private void txtnobukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnobukuActionPerformed

    }//GEN-LAST:event_txtnobukuActionPerformed

    private void txtnobukuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnobukuKeyPressed
        while (true){
            if(txtnobuku.getText().matches("[0-9]*")){
                if(evt.getKeyCode()==10){
                txtnamapenerbit.requestFocus();
                }
                break; 
            }else{
                JOptionPane.showMessageDialog(null, "Input harus angka!");
                txtnobuku.setText(null);
                txtnobuku.requestFocus();
                break;
            }
           
        } 
    }//GEN-LAST:event_txtnobukuKeyPressed

    private void txtstokKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstokKeyPressed
          while (true){
            if(txtstok.getText().matches("[0-9]*")){
                if(evt.getKeyCode()==10){
                txtharga.requestFocus();
                }
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Input harus angka!");
                txtstok.setText(null);
                txtstok.requestFocus();
                break;
            }      
        }
    }//GEN-LAST:event_txtstokKeyPressed

    private void createKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_createKeyPressed
                // TODO add your handling code here:
    }//GEN-LAST:event_createKeyPressed

    private void txthargaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthargaKeyPressed
        while (true){
            if(txtharga.getText().matches("[0-9]*")){
                if(evt.getKeyCode()==10){
                combojenis.requestFocus();
                }
                break; 
            }else{
                JOptionPane.showMessageDialog(null, "Input harus angka!");
                txtharga.setText(null);
                txtharga.requestFocus(); 
                break;
            }
           
        }                
    }//GEN-LAST:event_txthargaKeyPressed

    private void txthargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthargaActionPerformed

    }//GEN-LAST:event_txthargaActionPerformed

    private void txtjudulKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjudulKeyPressed
        if(evt.getKeyCode()==10){
            while (true){
            if(txtjudul.getText().matches("[a-zA-Z ]+")){
                txtstok.requestFocus();
                break;
            }else if(txtjudul.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtjudul.requestFocus();
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtjudul.setText(null);
                txtjudul.requestFocus();
                break;
            } 
        } 
        }
    }//GEN-LAST:event_txtjudulKeyPressed

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed

    }//GEN-LAST:event_txtjudulActionPerformed

    private void txtjudulKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjudulKeyTyped

    }//GEN-LAST:event_txtjudulKeyTyped

    private void txtnobukuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnobukuKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnobukuKeyReleased

    private void txtnamapenerbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapenerbitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapenerbitActionPerformed

    private void txtnamapenulisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamapenulisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamapenulisActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void txtnamapenerbitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamapenerbitKeyPressed
        if(evt.getKeyCode()==10){
            while (true){
            if(txtnamapenerbit.getText().matches("[a-zA-Z]+")){
                txtnamapenulis.requestFocus();
                break;
            }else if(txtnamapenerbit.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtnamapenerbit.requestFocus();
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtnamapenerbit.setText(null);
                txtnamapenerbit.requestFocus();
                break;
            } 
          } 
        }
    }//GEN-LAST:event_txtnamapenerbitKeyPressed

    private void txtnamapenulisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamapenulisKeyPressed
        if(evt.getKeyCode()==10){
            while (true){
            if(txtnamapenulis.getText().matches("[a-zA-Z ]+")){
                txtjudul.requestFocus();
                break;
            }else if(txtnamapenulis.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtnamapenulis.requestFocus();
                break;
            }else{
                JOptionPane.showMessageDialog(null, "Input harus huruf!");
                txtnamapenulis.setText(null);
                txtnamapenulis.requestFocus();
                break;
            } 
          } 
        }        
    }//GEN-LAST:event_txtnamapenulisKeyPressed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        try{
            int opsi = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Message", JOptionPane.YES_NO_OPTION);
            switch(opsi){
                case JOptionPane.YES_OPTION:
                    String sql = "TRUNCATE TABLE data_buku;";
                    java.sql.Connection connect = (Connection)koneksi.configDB();
                    java.sql.PreparedStatement pstm = connect.prepareStatement(sql);
                    pstm.execute();
                    JOptionPane.showMessageDialog(null, "Data berhasil di Reset");
                    break;
                case JOptionPane.NO_OPTION:
                    JOptionPane.showMessageDialog(null, "Okeh :) ");
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        showdata();
        reset_kolom();
    }//GEN-LAST:event_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JComboBox<String> combojenis;
    private javax.swing.JButton create;
    private javax.swing.JButton delete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton reset;
    private javax.swing.JTable tabel_buku;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtnamapenerbit;
    private javax.swing.JTextField txtnamapenulis;
    private javax.swing.JTextField txtnobuku;
    private javax.swing.JTextField txtstok;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
    private void scalenow(){
        sig s = new sig();
        jLabel8.setIcon(s.Scale(jLabel8, "gambar/wallpaperflare.com_wallpaper (2).jpg"));
    }
}
