import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import lib.*;
//import javax.swing.ImageIcon;

public class lojin extends javax.swing.JFrame {

    /**
     * Creates new form lojin
     */
    public lojin() {
        initComponents();
        scalenow();
    }
    public Connection conn;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bttnkeluar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        txtpw = new javax.swing.JPasswordField();
        submit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Database_Buku.exe");
        setBackground(new java.awt.Color(0, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jPanel3.setBackground(new java.awt.Color(153, 50, 204));
        jPanel3.setForeground(new java.awt.Color(51, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bttnkeluar.setBackground(new java.awt.Color(45, 49, 52));
        bttnkeluar.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        bttnkeluar.setForeground(new java.awt.Color(153, 50, 204));
        bttnkeluar.setText("Keluar");
        bttnkeluar.setBorder(null);
        bttnkeluar.setContentAreaFilled(false);
        bttnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnkeluarActionPerformed(evt);
            }
        });
        jPanel2.add(bttnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 70, 20));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 50, 204));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 200, 30));

        txtnama.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtnama.setForeground(new java.awt.Color(51, 51, 51));
        txtnama.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });
        txtnama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamaKeyPressed(evt);
            }
        });
        jPanel2.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, -1));

        txtpw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtpw.setForeground(new java.awt.Color(51, 51, 51));
        txtpw.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(153, 153, 153)));
        txtpw.setCaretColor(new java.awt.Color(255, 255, 255));
        txtpw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpwActionPerformed(evt);
            }
        });
        txtpw.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpwKeyPressed(evt);
            }
        });
        jPanel2.add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, -1));

        submit.setBackground(new java.awt.Color(45, 49, 52));
        submit.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(153, 50, 204));
        submit.setText("Masuk");
        submit.setBorder(null);
        submit.setContentAreaFilled(false);
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 70, 20));

        jLabel3.setBackground(new java.awt.Color(153, 50, 204));
        jLabel3.setFont(new java.awt.Font("Futura Md BT", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 50, 204));
        jLabel3.setText("Hello! Admin");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 90, 30));

        jLabel5.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 50, 204));
        jLabel5.setText("Good Morning");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 160, -1));

        jLabel6.setBackground(new java.awt.Color(153, 50, 204));
        jLabel6.setFont(new java.awt.Font("Futura Md BT", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 50, 204));
        jLabel6.setText("Username");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 280, 40));

        jLabel7.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 50, 204));
        jLabel7.setText("Login");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 60, -1));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 270, 280));

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnkeluarActionPerformed
        try{
            //menampilkan Optionpane yes no untuk konfirmasi aktifitas
            int pilih = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin?", "Message", JOptionPane.YES_NO_OPTION);
            switch(pilih){
                case JOptionPane.YES_OPTION:
                    JOptionPane.showMessageDialog(null, "Terimakasih");
                    System.exit(0);
                    break;
                case JOptionPane.NO_OPTION:
                    break;
                default:
                    break;     
            }
        }catch(HeadlessException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_bttnkeluarActionPerformed

    private void txtnamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaKeyPressed
        // ketika selesai mengisi username dan menekan tombol enter user diarahkan mengisi password
        if(evt.getKeyCode()==10){
            txtpw.requestFocus();
        }       
    }//GEN-LAST:event_txtnamaKeyPressed

    private void txtpwKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpwKeyPressed

        if(evt.getKeyCode()==10){
            try{
               Connection c = koneksi.configDB();
               Statement s = c.createStatement();
               
               String sql ="SELECT * from data_user WHERE Username='"+ txtnama.getText()
                       +"' and Password='"+txtpw.getText()+"'";
               ResultSet r = s.executeQuery(sql);
               
               if(r.next()){
                   JOptionPane.showMessageDialog(null, "Login Berhasil");
                   new HalamanUtama().show();
                   this.dispose();
               }else{
                   JOptionPane.showMessageDialog(null, "Login gagal");
               }    txtpw.requestFocus();
            }catch(SQLException e){
                    System.out.println("error");
            }
        }   
    }//GEN-LAST:event_txtpwKeyPressed

    private void txtpwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpwActionPerformed
            // TODO add your handling code here:
    }//GEN-LAST:event_txtpwActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
           try{
               Connection c = koneksi.configDB();
               Statement s = c.createStatement();
               
               String sql ="SELECT * from data_user WHERE Username='"+ txtnama.getText()
                       +"' and Password='"+txtpw.getText()+"'";
               ResultSet r = s.executeQuery(sql);
               
               if(r.next()){
                   JOptionPane.showMessageDialog(null, "Login Berhasil");
                   new HalamanUtama().show();
                   this.dispose();
               }else{
                   JOptionPane.showMessageDialog(null, "Login gagal");
               }    txtpw.requestFocus();
           }catch(SQLException e){
                    System.out.println("error");
                    }
           

    }//GEN-LAST:event_submitActionPerformed

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    /**
     * @param args the command line arguments   
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lojin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lojin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lojin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lojin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new lojin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnkeluar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton submit;
    private javax.swing.JTextField txtnama;
    private javax.swing.JPasswordField txtpw;
    // End of variables declaration//GEN-END:variables
    private void scalenow(){
        sig s = new sig();
       jLabel4.setIcon(s.Scale(jLabel4, "gambar/aa.png"));
    }
}
